name: chedit
base: core24
version: "2.0.4"
summary: Chedit is a bare-bones retro GUI-based text editor
description: |
  Chedit pays homage to the classic MS-DOS Editor, but re-imagined with a modern interface and clean, responsive controls. Learn more at https://github.com/isaiahpettingill/edit

grade: stable
confinement: strict

apps:
  chedit:
    command: bin/chedit
    plugs:
      - home

parts:
  chedit:
    source: https://github.com/isaiahpettingill/edit.git
    source-type: git
    plugin: rust
    build-packages:
      - build-essential
